---

- name: second playbook 
  hosts: localhost
  become: true 
  
  tasks: 
  - name: executing simple ls 
    shell: "ls -lrt" 
    register : "output"
  - debug: var=output.stdout_lines
  - name: creating dir 
    file: 
      path: /home/cloud/test_dir
      state: directory
      createhome: yes
      group: cloud
      owner: cloud
  - name: creating file in new dir 
    file: 
      path: /home/cloud/test_dir/hello-world.py 
      state: present 
      group: cloud
      owner: cloud
  - name: installing apache
    apt: 
      name: apache2 
      state: present    
        
