---
  - name: "Playing with Ansible."
    hosts: localhost
    connection: local
    tasks:
#     - name: create file using the shell 
#       shell: "touch test.txt"
      
    - name: execute ls command 
      shell: "ls -l"
      register: "output" 
      
#     - name: create new file 
#       file: 
#         path: .
#         state: touch
#         mode: 755
#     - name: installing Apache2
#       apt: 
#         name: apache2
#         state: present
    - debug: var=output.stdout_lines
